services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.defaults
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - data:/app/data
    restart: unless-stopped

volumes:
  data:
